### ISSUE TITLE
Design the hierarchy of `Int` with interfaces

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#103]
## Description

Design a new hierarchy of integers with interfaces that should be available on all platforms.
> See the following issue for more information about his structure: #98.

## Checklist

- [x] Design and comment the hierarchy below.
- [x] Create an issue for implementing the `IntHolder` type (see #106).
- [x] Create an issue for implementing the `ZeroInt` type (see #108).
- [x] Update the issue for implementing the `NonZeroInt` type (see #84).
- [x] Update the issue for implementing the `PositiveInt` type (see #85).
- [x] Update the issue for implementing the `NegativeInt` type (see #86).
- [x] Update the issue for implementing the `StrictlyPositiveInt` type (see #87).
- [x] Update the issue for implementing the `StrictlyNegativeInt` type (see #88).

**Comment by LVMVRQUXL** [comment]
Here's an example of a hierarchy of integers:
```kotlin
sealed interface Int : Number<kotlin.Int>

sealed interface NonZeroInt : Int, NonZeroNumber<kotlin.Int>
sealed interface PositiveInt : Int, PositiveNumber<kotlin.Int>
sealed interface NegativeInt : Int, NegativeNumber<kotlin.Int>

sealed interface StrictlyPositiveInt : Int,
    NonZeroInt,
    PositiveInt,
    StrictlyPositiveNumber<kotlin.Int>

sealed interface StrictlyNegativeInt : Int,
    NonZeroInt,
    NegativeInt,
    StrictlyNegativeNumber<kotlin.Int>
```

**Comment by LVMVRQUXL** [comment]
Here is a better example of a hierarchy of integers using composition over inheritance:
```kotlin
// ---------- Int ----------

interface IntHolder {
    val value: Int
    val validator: IntValidator?

    operator fun plus(other: Int): Int
}

class IntHolderImplementation(
    override val value: Int,
    override val validator: IntValidator? = null
) : IntHolder,
    Comparable<IntHolder> {
    init {
        validator?.let { require(it isValid value) }
    }

    override fun compareTo(other: IntHolder): Int =
        value.compareTo(other.value)

    override fun plus(other: Int): Int = value + other
    override fun toString(): String = "IntHolder(value = $value)"
}

fun interface IntValidator {
    infix fun isValid(value: Int): Boolean
    infix fun isNotValid(value: Int): Boolean = !isValid(value)
}

// ---------- ZeroInt ----------

const val ZERO: Int = 0

interface ZeroInt : IntHolder
object ZeroIntImplementation : ZeroInt,
    IntHolder by IntHolderImplementation(ZERO, ZeroIntValidatorImplementation) {
    override val value: Int = ZERO
}

fun interface ZeroIntValidator : IntValidator
object ZeroIntValidatorImplementation : ZeroIntValidator {
    override fun isValid(value: Int): Boolean = value == ZERO
}

// ---------- NonZeroInt ----------

fun NonZeroInt(value: Int): NonZeroInt = NonZeroIntImplementation(value)

@Suppress("FunctionName")
fun NonZeroIntOrNull(value: Int): NonZeroInt? = try {
    NonZeroInt(value)
} catch (_: IllegalArgumentException) {
    null
}

interface NonZeroInt : IntHolder
class NonZeroIntImplementation(override val value: Int) :
    NonZeroInt,
    IntHolder by IntHolderImplementation(
        value,
        NonZeroIntValidatorImplementation
    )

fun interface NonZeroIntValidator : IntValidator
object NonZeroIntValidatorImplementation : NonZeroIntValidator {
    override fun isValid(value: Int): Boolean =
        ZeroIntValidatorImplementation isNotValid value
}

// ---------- PositiveInt ----------

fun PositiveInt(value: Int): PositiveInt =
    PositiveIntImplementation(value)

@Suppress("FunctionName")
fun PositiveIntOrNull(value: Int): PositiveInt? = try {
    PositiveInt(value)
} catch (_: IllegalArgumentException) {
    null
}

interface PositiveInt : IntHolder
class PositiveIntImplementation(override val value: Int) :
    PositiveInt,
    IntHolder by IntHolderImplementation(
        value,
        PositiveIntValidatorImplementation
    )

fun interface PositiveIntValidator : IntValidator
object PositiveIntValidatorImplementation : PositiveIntValidator {
    override fun isValid(value: Int): Boolean =
        value >= ZeroIntImplementation.value
}

// ---------- NegativeInt ----------

fun NegativeInt(value: Int): NegativeInt =
    NegativeIntImplementation(value)

@Suppress("FunctionName")
fun NegativeIntOrNull(value: Int): NegativeInt? = try {
    NegativeInt(value)
} catch (_: IllegalArgumentException) {
    null
}

interface NegativeInt : IntHolder
class NegativeIntImplementation(override val value: Int) :
    NegativeInt,
    IntHolder by IntHolderImplementation(
        value,
        NegativeIntValidatorImplementation
    )

fun interface NegativeIntValidator : IntValidator
object NegativeIntValidatorImplementation : NegativeIntValidator {
    override fun isValid(value: Int): Boolean =
        value <= ZeroIntImplementation.value
}

// ---------- StrictlyPositiveInt ----------

fun StrictlyPositiveInt(value: Int): StrictlyPositiveInt =
    StrictlyPositiveIntImplementation(value)

interface StrictlyPositiveInt : IntHolder
class StrictlyPositiveIntImplementation(override val value: Int) :
    StrictlyPositiveInt,
    IntHolder by IntHolderImplementation(
        value,
        StrictlyPositiveIntValidatorImplementation
    )

fun interface StrictlyPositiveIntValidator : IntValidator
object StrictlyPositiveIntValidatorImplementation :
    StrictlyPositiveIntValidator {
    override fun isValid(value: Int): Boolean = value > 0
}

// ---------- StrictlyNegativeInt ----------

fun StrictlyNegativeInt(value: Int): StrictlyNegativeInt =
    StrictlyNegativeIntImplementation(value)

interface StrictlyNegativeInt : IntHolder
class StrictlyNegativeIntImplementation(override val value: Int) :
    StrictlyNegativeInt,
    IntHolder by IntHolderImplementation(
        value,
        StrictlyNegativeIntValidatorImplementation
    )

fun interface StrictlyNegativeIntValidator : IntValidator
object StrictlyNegativeIntValidatorImplementation :
    StrictlyNegativeIntValidator {
    override fun isValid(value: Int): Boolean = value < 0
}
```

**Comment by LVMVRQUXL** [comment]
Done.
