### ISSUE TITLE
New builders suffixed by `OrNull`

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#107]
## Description

Like discussed in #104, we would like to introduce **experimental** builders suffixed by `OrNull` for all existing types.

> These builders should be marked by the experimental annotation corresponding to their package.

Here's an example for the `NonZeroInt` type:

```kotlin

package kotools.types.number

import kotools.types.experimental.ExperimentalNumberApi

/**
 * Returns this number as a [NonZeroInt], which may involve rounding or
 * truncation, or returns `null` if this number equals zero.
 */
@ExperimentalNumberApi
fun Number.toNonZeroIntOrNull(): NonZeroInt? = TODO("Not implemented")

println(1.toNonZeroIntOrNull()) // 1
println(0.toNonZeroIntOrNull()) // null
```

## Checklist

- [x] Create the issue #132.
- [x] Create the issue #141.
- [x] Create the issue #149.
- [x] Create the issue #155.
- [ ] Create an issue for the `NegativeInt` type.
- [ ] Create an issue for the `NonZeroInt` type.
- [ ] Create an issue for the `NotBlankString` type.
- [ ] Create an issue for the `NotEmptyList` type.
- [ ] Create an issue for the `NotEmptySet` type.
- [ ] Create an issue for the `NotEmptyMap` type.
- [ ] Create an issue for updating the `Unreleased` section in changelog.

**Comment by LVMVRQUXL** [comment]
The issue #132 will implement this builder for the `StrictlyPositiveDouble` type.

**Comment by LVMVRQUXL** [comment]
We should split this issue by type.

**Comment by LVMVRQUXL** [comment]
We will implement the builder for the `StrictlyPositiveInt` type in the issue #141.
