### ISSUE TITLE
Java compatibility with inline value classes

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#153]
## Description

When declaring an [inline value class] in Kotlin, the functions receiving it as a parameter are [mangled][mangling] by adding a stable hash code to the function name.

```kotlin
@JvmInline
value class UInt(val x: Int)

// Represented as 'public final void compute(int x)' on the JVM.
fun compute(x: Int) { }

// Represented as 'public final void compute-<hashcode>(int x)' on the JVM.
fun compute(x: UInt) { }
```

This solution provided by the language makes these functions incompatible with Java: we can't call a function with an invalid identifier.
For [disabling mangling] and bringing Java compatibility to these functions, we should mark them with the `JvmName` annotation.

```kotlin
@JvmInline
value class UInt(val x: Int)

// Represented as 'public final void compute(int x)' on the JVM.
fun compute(x: Int) { }

// Represented as 'public final void computeUInt(int x)' on the JVM.
@JvmName("computeUInt")
fun compute(x: UInt) { }
```

[inline value class]: https://kotlinlang.org/docs/inline-classes.html
[mangling]: https://kotlinlang.org/docs/inline-classes.html#mangling
[disabling mangling]: https://kotlinlang.org/docs/inline-classes.html#calling-from-java-code

## Checklist

- [ ] Identify types declared as [inline value class] and there usages.
- [ ] Create an issue for each types identified and add it in the `Subtasks` checklist below.
- [ ] Change the status of this issue to `Blocked` and wait for the resolution of all subtasks.
- [ ] Update the `Unreleased > Added` section in changelog.

### Subtasks

- [x] #154

**Comment by LVMVRQUXL** [comment]
For testing the Java compatibility of the library, we will [enable the use of Java sources in JVM compilations](https://kotlinlang.org/docs/multiplatform-configure-compilations.html#use-java-sources-in-jvm-compilations).

**Comment by LVMVRQUXL** [comment]
This issue moved to the discussion #156 for a [better process following](https://github.com/kotools/types/blob/main/CONTRIBUTING.md#feature-suggestion).
