### ISSUE TITLE
Documentation of declarations returning `Result`

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#20]
## Description

Update the documentation of declarations returning a `Result` type by mentioning that the result is encapsulated.
Here's an example for the [`String.toNotBlankString`](https://kotools.github.io/types/types/kotools.types.text/index.html#-2124605309%2FFunctions%2F788909594) function:
```kotlin
/**
 * Returns this string as an encapsulated [NotBlankString], or returns an
 * encapsulated [IllegalArgumentException] if this string is blank.
 */
public fun String.toNotBlankString(): Result<NotBlankString> = TODO()
```

## Checklist

- [x] Update the documentation of the [`String.toNotBlankString`](https://kotools.github.io/types/types/kotools.types.text/index.html#-2124605309%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Int.toNonZeroInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1910610539%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Int.toPositiveInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1567430823%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Int.toNegativeInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-667169643%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Int.toStrictlyPositiveInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#1816914703%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Int.toStrictlyNegativeInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1577791413%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Collection.toNotEmptyList`](https://kotools.github.io/types/types/kotools.types.collection/index.html#392718672%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Collection.toNotEmptySet`](https://kotools.github.io/types/types/kotools.types.collection/index.html#309854186%2FFunctions%2F788909594) function.
- [x] Update the documentation of the [`Map.toNotEmptyMap`](https://kotools.github.io/types/types/kotools.types.collection/index.html#-157373950%2FFunctions%2F788909594) function.
- [x] Update changelog.

**Comment by LVMVRQUXL** [comment]
Actually, this is not a bug but an enhancement.

**Comment by LVMVRQUXL** [comment]
We will also integrate those changes in [Kotools Types 4.0.1](https://github.com/kotools/types/milestone/6).

**Comment by LVMVRQUXL** [comment]
We should put those changes in the changelog.
