### ISSUE TITLE
New builders suffixed by `OrNull` or `OrThrow`

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#22]
## Description

Introduce more builders suffixed by `OrNull` or `OrThrow`.
Here's an example for the [`String.toNotBlankString`](https://kotools.github.io/types/types/kotools.types.text/index.html#-2124605309%2FFunctions%2F788909594) function:

```kotlin
/**
 * Returns this string as a [NotBlankString], or returns `null` if this string
 * is blank.
 */
fun String.toNotBlankStringOrNull(): NotBlankString? = TODO()

/**
 * Returns this string as a [NotBlankString], or throws an
 * [IllegalArgumentException] if this string is blank.
 */
@Throws(IllegalArgumentException::class)
fun String.toNotBlankStringOrThrow(): NotBlankString = TODO()
```

## Checklist

- [x] Implement for the [`String.toNotBlankString`](https://kotools.github.io/types/types/kotools.types.text/index.html#-2124605309%2FFunctions%2F788909594) function.
- [x] Implement for the [`Int.toNonZeroInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1910610539%2FFunctions%2F788909594) function.
- [x] Implement for the [`Int.toPositiveInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1567430823%2FFunctions%2F788909594) function.
- [x] Implement for the [`Int.toNegativeInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-667169643%2FFunctions%2F788909594) function.
- [x] Implement for the [`Int.toStrictlyPositiveInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#1816914703%2FFunctions%2F788909594) function.
- [x] Implement for the [`Int.toStrictlyNegativeInt`](https://kotools.github.io/types/types/kotools.types.number/index.html#-1577791413%2FFunctions%2F788909594) function.
- [x] Implement for the [`Collection.toNotEmptyList`](https://kotools.github.io/types/types/kotools.types.collection/index.html#392718672%2FFunctions%2F788909594) function.
- [x] Implement for the [`Collection.toNotEmptySet`](https://kotools.github.io/types/types/kotools.types.collection/index.html#309854186%2FFunctions%2F788909594) function.
- [x] Implement for the [`Map.toNotEmptyMap`](https://kotools.github.io/types/types/kotools.types.collection/index.html#-157373950%2FFunctions%2F788909594) function.
- [x] Test.
- [x] Refactor.
- [x] Update `Work in progress` section in changelog.
- [x] Update code sample in readme.

**Comment by LVMVRQUXL** [comment]
We will not implement this issue because users should externalize or handle errors at the end of their process:

```kotlin
import kotools.types.text.NotBlankString
import kotools.types.text.toNotBlankString

fun main() {
    // Bad
    val kotools: NotBlankString = "Kotools".toNotBlankString()
        .getOrThrow()
    val types: NotBlankString = "Types".toNotBlankString()
        .getOrThrow()
    println("$kotools $types") // "Kotools Types"

    // Good
    "Kotools".toNotBlankString()
        .mapCatching { "$it Types".toNotBlankString().getOrThrow() }
        .getOrThrow()
        .let(::println) // "Kotools Types"
}
```

**Comment by LVMVRQUXL** [comment]
Those functions could be useful for users and internally if they want to implement their logic in the imperative style.

**Comment by LVMVRQUXL** [comment]
We will not implement those changes for now: we letting users decide how to handle errors using the [`Result`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) type.
