### ISSUE TITLE
Binary operations for `AnyInt` hierarchy

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#31]
## Description

Implement binary operations for the [`AnyInt`](https://kotools.github.io/types/types/kotools.types.number/-any-int/index.html) hierarchy.

## Checklist

- [x] Implement the [`plus`](https://github.com/kotools/types/issues/31#issuecomment-1413539426) operations.
- [x] Implement the [`minus`](https://github.com/kotools/types/issues/31#issuecomment-1413541735) operations.
- [x] Implement the [`times`](https://github.com/kotools/types/issues/31#issuecomment-1414248962) operations.
- [x] Implement the [`div`](https://github.com/kotools/types/issues/31#issuecomment-1414283311) operations.
- [x] Implement the [`rem`](https://github.com/kotools/types/issues/31#issuecomment-1414297124) operations.
- [x] Refactor code.
- [x] Update the `Unreleased` section in changelog.

**Comment by LVMVRQUXL** [comment]
We should also introduce binary operations using the [`Int`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/index.html) type as a parameter or receiver for a better integration with the standard library.

**Comment by LVMVRQUXL** [comment]
Here is the list of `plus` operations to implement:

```kotlin
/** Adds the [other] integer to this one. */
operator fun Int.plus(other: AnyInt): Int
operator fun AnyInt.plus(other: Int): Int
operator fun AnyInt.plus(other: AnyInt): Int
```

**Comment by LVMVRQUXL** [comment]
Here's the list of `minus` operations to implement:

```kotlin
/** Subtracts the [other] integer from this one. */
operator fun Int.minus(other: AnyInt): Int
operator fun AnyInt.minus(other: Int): Int
operator fun AnyInt.minus(other: AnyInt): Int
```

**Comment by LVMVRQUXL** [comment]
Here's the list of `times` operations to implement:

```kotlin
/** Multiplies this integer by the [other] one. */
operator fun Int.times(other: AnyInt): Int
operator fun AnyInt.times(other: Int): Int
operator fun AnyInt.times(other: AnyInt): Int
```

**Comment by LVMVRQUXL** [comment]
Here's the list of `div` operations to implement:

```kotlin
/**
 * Divides this integer by the [other] one, truncating the result to an integer
 * that is closer to [zero][ZeroInt].
 */
operator fun Int.div(other: NonZeroInt): Int
operator fun AnyInt.div(other: NonZeroInt): Int
operator fun PositiveInt.div(other: StrictlyPositiveInt): PositiveInt
operator fun PositiveInt.div(other: StrictlyNegativeInt): NegativeInt
operator fun NegativeInt.div(other: StrictlyPositiveInt): NegativeInt
operator fun NegativeInt.div(other: StrictlyNegativeInt): PositiveInt
```

**Comment by LVMVRQUXL** [comment]
Here's the list of `rem` operations to implement:

```kotlin
/**
 * Calculates the remainder of truncating division of this integer by the
 * [other] one.
 */
operator fun Int.rem(other: NonZeroInt): Int
operator fun AnyInt.rem(other: NonZeroInt): Int
operator fun PositiveInt.rem(other: NonZeroInt): PositiveInt
operator fun NegativeInt.rem(other: NonZeroInt): NegativeInt
```

**Comment by LVMVRQUXL** [comment]
Those changes will not be implemented according to our [design principles](https://github.com/kotools/types#design-goals).

**Comment by LVMVRQUXL** [comment]
Implementing those changes will simplify the usage of the `AnyInt` hierarchy.
```kotlin
val x: NonZeroInt = NonZeroInt.random()
val y: PositiveInt = PositiveInt.random()
var result: Int
// before
result = x.toInt() + 1
result = 1 + x.toInt()
result = x.toInt() + y.toInt()
// after
result = x + 1
result = 1 + x
result = x + y
```

**Comment by LVMVRQUXL** [comment]
Will not be implemented (see [this comment](https://github.com/kotools/types/issues/31#issuecomment-1427057523)).

**Comment by LVMVRQUXL** [comment]
Because those operations were implemented in its dedicated branch (`feature/31`), we will keep it open until the corresponding branch will be merged.
