### ISSUE TITLE
💡 Creating `topic` issues from idea discussions

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#585]
## 📝 Description

We would like to create `topic` issues from discussions for improving our progress tracking on those topics.
This way, we will dedicate the GitHub discussions for communicating with our community.
Creating an issue for a topic also indicates that we are engaging to implement the corresponding evolution.

## ✅ Checklist

- [x] Create a dedicated label.
- [x] Create a dedicated view in the private project.
- [x] Create a topic issue for discussion #55, then close this discussion as completed.
- [x] Create a GitHub issue template for topics.
- [x] Create a topic issue for discussion #335, then close this discussion as completed.
- [x] Create a topic issue for discussion #28, then close this discussion as completed.
- [x] Create a topic issue for discussion #39, then close this discussion as completed.
- [x] Close this issue as completed and update tracking ones if present.
