### ISSUE TITLE
Design the hierarchy of `Number` with interfaces

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#98]
## Description

Design a new hierarchy of numbers with interfaces that should be availble for all platforms.
The `Number` hierarchy should contain the following types:
- `Number` representing numeric values
- `NonZeroNumber` representing numbers that don't equal `0`
- `PositiveNumber` representing positive numbers including `0` (cf. `x >= 0`)
- `NegativeNumber` representing negative numbers including `0` (cf. `x <= 0`)
- `StrictlyPositiveNumber` representing positive numbers excluding `0` (cf. `x > 0`)
- `StrictlyNegativeNumber` representing negative numbers excluding `0` (cf. `x < 0`).
> The `Int` hierarchy should have the same structure of the `Number` one!

## Checklist

- [x] Design and comment the hierarchy below.
- [x] Create an issue for implementing the `Number` type (see #99).
- [x] Create an issue for implementing the `NonZeroNumber` type (see #100).
- [x] Create an issue for implementing the `PositiveNumber` type (see #101).
- [x] Create an issue for implementing the `NegativeNumber` type (see #102).
- [x] Create an issue for implementing the `StrictlyPositiveNumber` type (see #104).
- [x] Create an issue for implementing the `StrictlyNegativeNumber` type (see #105).

**Comment by LVMVRQUXL** [comment]
Here is an example of a hierarchy of numbers:
```kotlin
package kotools.types.number

// ---------- Number ----------

public sealed interface Number<T : kotlin.Number> {
    public val value: T
}

public sealed interface NonZeroNumber<T : kotlin.Number> : Number<T>
public sealed interface PositiveNumber<T : kotlin.Number> : Number<T>
public sealed interface NegativeNumber<T : kotlin.Number> : Number<T>

public sealed interface StrictlyPositiveNumber<T : kotlin.Number> :
    NonZeroNumber<T>,
    PositiveNumber<T>

public sealed interface StrictlyNegativeNumber<T : kotlin.Number> :
    NonZeroNumber<T>,
    NegativeNumber<T>

// ---------- Int ----------

public sealed interface Int : Number<kotlin.Int>

public sealed interface NonZeroInt2 : Int, NonZeroNumber<kotlin.Int>
public sealed interface PositiveInt2 : Int, PositiveNumber<kotlin.Int>
public sealed interface NegativeInt2 : Int, NegativeNumber<kotlin.Int>

public sealed interface StrictlyPositiveInt2 : Int,
    NonZeroInt2,
    PositiveInt2,
    StrictlyPositiveNumber<kotlin.Int>

public sealed interface StrictlyNegativeInt2 : Int,
    NonZeroInt2,
    NegativeInt2,
    StrictlyNegativeNumber<kotlin.Int>
```

**Comment by LVMVRQUXL** [comment]
Done.

**Comment by LVMVRQUXL** [comment]
Don't include this issue in the version 3.0.0. We will focus on the `Int` hierarchy instead.
